<?php

class PxlPortfolioInfo_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_portfolio_info';
    protected $title = 'PXL Portfolio Info';
    protected $icon = 'eicon-info-circle-o';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"content_section","label":"Content Settings","tab":"content","controls":[{"name":"heading_title","label":"Heading Title","type":"text","placeholder":"Enter heading title","default":"Project details","label_block":true},{"name":"portfolio_infos","label":"Portfolio Information Lists","type":"repeater","controls":[{"name":"item_label","label":"Item Label","type":"text","placeholder":"Enter item label","default":"Name:","label_block":true},{"name":"item_value","label":"Item Value","type":"text","placeholder":"Enter item value","default":"Rob\'s Farm","label_block":true}],"default":[{"item_label":"Name:","item_value":"Rob\'s Farm"},{"item_label":"Date:","item_value":"24th March 2020"},{"item_label":"Author:","item_value":"Marilin De Aragon"},{"item_label":"Tag:","item_value":"UI\/Ux Design"}]},{"name":"value_title","label":"Value Title","type":"text","placeholder":"Enter value title","default":"Value:&nbsp;&nbsp;&nbsp;$&nbsp;125 ","label_block":true},{"name":"rating","label":"Rating","type":"number","placeholder":"Enter the rating (1-5)","default":5,"label_block":true}]},{"name":"pi_style","label":"Style","tab":"style","controls":[{"name":"heading_bg","label":"Heading Background","type":"color","selectors":{"{{WRAPPER}} .pi-heading":"background-color: {{VALUE}};"}},{"name":"heading_color","label":"Heading Color","type":"color","selectors":{"{{WRAPPER}} .pi-heading":"color: {{VALUE}};"}},{"name":"content_bg","label":"Content Background","type":"color","selectors":{"{{WRAPPER}} .pi-content":"background-color: {{VALUE}};"}},{"name":"content_color","label":"Content Color","type":"color","selectors":{"{{WRAPPER}} .pi-content":"color: {{VALUE}};"}},{"name":"lbl_color","label":"Label Color","type":"color","selectors":{"{{WRAPPER}} .pi-lbl":"color: {{VALUE}};"}},{"name":"lbl_typo","label":"Label Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pi-lbl"},{"name":"value_title_color","label":"Value Title Color","type":"color","selectors":{"{{WRAPPER}} .pi-vl-title":"color: {{VALUE}};"}},{"name":"value_title_typo","label":"Value Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pi-vl-title"},{"name":"item_animation","label":"Item Motion Effect","type":"animation","condition":[]},{"name":"item_animation_duration","label":"Item Animation Duration","type":"select","default":"normal","options":{"slow":"Slow","normal":"Normal","fast":"Fast"},"condition":{"item_animation!":""}},{"name":"item_animation_delay","label":"Item Animation Delay","type":"number","min":0,"step":100,"condition":{"item_animation!":""}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}