<?php

class PxlFancyBox_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_fancy_box';
    protected $title = 'PXL Fancy Box';
    protected $icon = 'eicon-icon-box';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"https:\/\/lawyermolochko.ddev.site:8443\/wp-content\/themes\/powerlegal\/elements\/assets\/layout-image\/pxl_fancy_box-1.jpg"},"2":{"label":"Layout 2","image":"https:\/\/lawyermolochko.ddev.site:8443\/wp-content\/themes\/powerlegal\/elements\/assets\/layout-image\/pxl_fancy_box-2.jpg"},"3":{"label":"Layout 3","image":"https:\/\/lawyermolochko.ddev.site:8443\/wp-content\/themes\/powerlegal\/elements\/assets\/layout-image\/pxl_fancy_box-3.jpg"},"4":{"label":"Layout 4","image":"https:\/\/lawyermolochko.ddev.site:8443\/wp-content\/themes\/powerlegal\/elements\/assets\/layout-image\/pxl_fancy_box-4.jpg"},"5":{"label":"Layout 5","image":"https:\/\/lawyermolochko.ddev.site:8443\/wp-content\/themes\/powerlegal\/elements\/assets\/layout-image\/pxl_fancy_box-5.jpg"}}}]},{"name":"content_section","label":"Content","tab":"content","controls":[{"name":"selected_icon","label":"Icon","type":"icons","default":{"library":"flaticon","value":"flaticon-calling"},"condition":{"layout!":["2"]}},{"name":"icon_size","label":"Icon Size","type":"slider","range":{"px":{"min":15,"max":300}},"selectors":{"{{WRAPPER}} .pxl-fancy-box .box-icon i":"font-size: {{SIZE}}{{UNIT}};","{{WRAPPER}} .pxl-fancy-box .box-icon svg":"width: {{SIZE}}{{UNIT}} !important;"},"condition":{"layout!":["2"]}},{"name":"icon_margin","label":"Icon Margin","type":"dimensions","size_units":["px"],"selectors":{"{{WRAPPER}} .pxl-fancy-box .box-icon i":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};","{{WRAPPER}} .pxl-fancy-box .box-icon svg":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"control_type":"responsive","condition":{"layout!":["2"]}},{"name":"selected_img","label":"Image","type":"media","default":"","condition":{"layout":["2","4"]}},{"name":"title","label":"Title","type":"textarea","default":"Your Title"},{"name":"description","label":"Description","type":"textarea","default":"Lorem Ipsum is simply dummy text of the printing and typesetting industry"},{"name":"link","label":"Custom Link","type":"url","placeholder":"https:\/\/your-link.com","default":{"url":"#","is_external":"on"},"condition":{"layout!":["2"]}},{"name":"button_text","label":"Button Text","type":"text","label_block":true,"condition":{"layout":["4"]}},{"name":"item_index","label":"Item Index","type":"number","default":"1","min":"1","max":"7","condition":{"layout":["3"]}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}