<?php

class PxlHeaderFactor_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_header_factor';
    protected $title = 'Pxl Header factor';
    protected $icon = 'eicon-cart';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/widgets\/img-layout\/pxl_header_factor-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/widgets\/img-layout\/pxl_header_factor-2.jpg"}},"prefix_class":"pxl-header-factor-layout-"}]},{"name":"content_section","label":"Setting","tab":"content","controls":[{"name":"content_align","label":"Content Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-header-factor .header-factor-inner":"justify-content: {{VALUE}};"},"condition":{"layout":"1"}},{"name":"on_search","label":"Show Search","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .pxl-header-factor.layout-1 .pxl-search":"display: {{VALUE}}!important;"}},{"name":"search_type","label":"Search Type","type":"select","options":{"normal":"Search Normal","product":"Search Product"},"default":"normal","condition":{"on_search":["inline-flex","none"]}},{"name":"on_user","label":"Show User","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .pxl-header-factor.layout-1 .pxl-user":"display: {{VALUE}}!important;"}},{"name":"on_wishlist","label":"Show Wishlist","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .pxl-header-factor.layout-1 .pxl-wishlist":"display: {{VALUE}}!important;"}},{"name":"on_cart","label":"Show Cart","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .pxl-header-factor.layout-1 .pxl-cart":"display: {{VALUE}}!important;"}},{"name":"ft_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-factor":"color: {{VALUE}};"}},{"name":"ft_color_hover","label":"Hover Color","type":"color","selectors":{"{{WRAPPER}} .pxl-factor:hover":"color: {{VALUE}};"}},{"name":"class","label":"Class","type":"text","separator":"after"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}