<?php

class PxlAccordion_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_accordion';
    protected $title = 'PXL Accordion';
    protected $icon = 'eicon-accordion';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2","style3":"Style 3","style4":"Style 4"},"default":"style1"},{"name":"active_section","label":"Active section","type":"number","separator":"after","default":"1"},{"name":"ac_items","label":"Accordion Items","type":"repeater","controls":[{"name":"ac_title","label":"Title","type":"textarea","rows":3},{"name":"selected_icon","label":"Left Title Icon","type":"icons","default":{"library":"pxli","value":"pxli-auction"},"description":"Use for style4 only"},{"name":"ac_content_type","label":"Content Type","type":"select","default":"text_editor","options":{"text_editor":"Text Editor","template":"Template"}},{"name":"ac_content","label":"Content","type":"wysiwyg","show_label":false,"condition":{"ac_content_type":"text_editor"}},{"name":"ac_content_template","label":"Select Templates","description":"Please create your layout before choosing. <a href=\"https:\/\/lawyermolochko.ddev.site:8443\/wp-admin\/edit.php?post_type=pxl-template\">Click Here<\/a>","type":"select","default":"","options":{"0":"None","4602":"New York Office","4651":"Washington Office","5063":"History_01","5075":"History_02","5120":"History_03","5134":"History_04","5137":"History_05","5140":"History_06","5434":"Accordion_01","6085":"History_Accordion","6518":"About_Me_01","6531":"About_Me_02","7523":"Tab_Why_Choose_Us","7549":"Tab_Mission_Vision","7584":"Tab_History","7591":"Tab_Awards"},"condition":{"ac_content_type":"template"}}],"default":[{"ac_title":"FAQ Title #1","ac_content":"Lorem ipsum dolor sit amet consecte tur adipiscing elit sed do eiu smod tempor incididunt ut labore."},{"ac_title":"FAQ Title #2","ac_content":"Lorem ipsum dolor sit amet consecte tur adipiscing elit sed do eiu smod tempor incididunt ut labore."}],"title_field":"{{{ ac_title }}}","separator":"after"}]},{"name":"style_section","label":"Style","tab":"style","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-accordion .ac-item .ac-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-accordion .ac-item .ac-title"},{"name":"desc_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}} .pxl-accordion .ac-item .ac-desc":"color: {{VALUE}};"}},{"name":"desc_typography","label":"Description Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-accordion .ac-item .ac-desc"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'powerlegal-accordion' );
}