<?php

class PxlBanner_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_banner';
    protected $title = 'PXL Banner';
    protected $icon = 'eicon-image-rollover';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_banner-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_banner-2.jpg"}},"prefix_class":"pxl-banner-layout-"}]},{"name":"content_section","label":"Content","tab":"content","controls":[{"name":"image","label":"Image Large","type":"media"},{"name":"img_size","label":"Image Size Large","type":"text","description":"Enter image size (Example: \"thumbnail\", \"medium\", \"large\", \"full\" or other sizes defined by theme). Alternatively enter size in pixels (Example: 200x100 (Width x Height)."},{"name":"selected_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"library":"flaticon","value":"flaticon-ecological-2"}},{"name":"title","label":"Title","type":"text","default":"Your Title","label_block":true,"condition":{"layout":"1"}},{"name":"sub_title","label":"Sub Title","type":"textarea","default":"Sub Title","condition":{"layout":"1"}},{"name":"link","label":"Link","type":"url","label_block":true,"condition":{"layout":"1"}}]},{"name":"section_style_bn","label":"Style","tab":"style","controls":[{"name":"content_bg","label":"Content background","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .bn-content":"background-color: {{VALUE}};"}},{"name":"icon_color","label":"Feature Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .pxl-icon":"color: {{VALUE}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .bn-title":"color: {{VALUE}};"},"condition":{"layout":"1"}},{"name":"sub_title_color","label":"Sub Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .bn-sub-title":"color: {{VALUE}};"},"condition":{"layout":"1"}},{"name":"img_animation","label":"Image Motion Effect","type":"animation","condition":[]},{"name":"img_animation_duration","label":"Image Animation Duration","type":"select","default":"normal","options":{"slow":"Slow","normal":"Normal","fast":"Fast"},"condition":{"img_animation!":""}},{"name":"img_animation_delay","label":"Image Animation Delay","type":"number","min":0,"step":100,"condition":{"img_animation!":""}},{"name":"content_animation","label":"Content Motion Effect","type":"animation","condition":[]},{"name":"content_animation_duration","label":"Content Animation Duration","type":"select","default":"normal","options":{"slow":"Slow","normal":"Normal","fast":"Fast"},"condition":{"content_animation!":""}},{"name":"content_animation_delay","label":"Content Animation Delay","type":"number","min":0,"step":100,"condition":{"content_animation!":""}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}