<?php

class PxlLinks_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_links';
    protected $title = 'PXL Links';
    protected $icon = 'eicon-editor-link';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_links-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_links-2.jpg"},"3":{"label":"Layout 3","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_links-3.jpg"}},"prefix_class":"pxl-links-layout-"}]},{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"links","label":"Link items","type":"repeater","controls":[{"name":"text","label":"Text","type":"text","label_block":true},{"name":"link","label":"Link","type":"url","label_block":true}],"default":[{"text":"Our News","link":{"url":"#","is_external":"on"}}],"title_field":"{{{ text }}}"}]},{"name":"section_style_link","label":"Link","tab":"style","controls":[{"name":"align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-links":"justify-content: {{VALUE}};"}},{"name":"link_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-links a":"color: {{VALUE}};"}},{"name":"link_color_hover","label":"Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-links a:hover":"color: {{VALUE}};"}},{"name":"link_typography","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-links a"},{"name":"bottom_spacer","label":"Bottom Spacer","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-links li":"margin-bottom: {{SIZE}}{{UNIT}};"},"condition":{"layout":["1"]}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}