<?php

class PxlTabList_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_tab_list';
    protected $title = 'PXL Tab List';
    protected $icon = 'eicon-posts-grid';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_list","label":"Content","tab":"content","controls":[{"name":"img_size","label":"Image Size","type":"text","description":"Enter image size (Example: \"thumbnail\", \"medium\", \"large\", \"full\" or other sizes defined by theme). Alternatively enter size in pixels (Example: 200x100 (Width x Height)."},{"name":"content_list","label":"Content List","type":"repeater","controls":[{"name":"selected_img","label":"Image","type":"media","default":""},{"name":"title","label":"Title","type":"textarea","label_block":true},{"name":"hyper_link","label":"Custom Link","type":"url","placeholder":"https:\/\/your-link.com","default":{"url":"#","is_external":"on"}}],"title_field":"{{{ title }}}"}]},{"name":"style_section","label":"Style","tab":"content","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-tab-list .tl-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-tab-list .tl-title"},{"name":"number_color","label":"Number Color","type":"color","selectors":{"{{WRAPPER}} .pxl-tab-list .tl-title-wrap .num":"color: {{VALUE}};"}},{"name":"number_bg_color","label":"Number Background Color","type":"color","selectors":{"{{WRAPPER}} .pxl-tab-list .tl-title-wrap .num":"background-color: {{VALUE}};"}},{"name":"number_bg_color_hover","label":"Number Background Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-tab-list .tl-item:hover .tl-title-wrap .num, {{WRAPPER}} .pxl-tab-list .tl-item.active .tl-title-wrap .num":"background-color: {{VALUE}};"}},{"name":"item_animation","label":"Item Motion Effect","type":"animation","condition":[]},{"name":"item_animation_duration","label":"Item Animation Duration","type":"select","default":"normal","options":{"slow":"Slow","normal":"Normal","fast":"Fast"},"condition":{"item_animation!":""}},{"name":"item_animation_delay","label":"Item Animation Delay","type":"number","min":0,"step":100,"condition":{"item_animation!":""}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'powerlegal-tabs' );
}