<?php

class PxlPricingSingle_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_pricing_single';
    protected $title = 'PXL Pricing';
    protected $icon = 'eicon-price-table';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_list","label":"Content","tab":"content","controls":[{"name":"price_currency","label":"Currency","type":"text"},{"name":"price_value","label":"Price","type":"text"},{"name":"price_duration","label":"Duration","type":"text"},{"name":"title","label":"Title","type":"text","placeholder":"Enter your title","label_block":true},{"name":"content_list","label":"Feature","type":"repeater","controls":[{"name":"content","label":"Content","type":"text","label_block":true},{"name":"active","label":"Active","type":"select","options":{"no":"No","yes":"Yes"},"default":"yes"}],"title_field":"{{{ content }}}"},{"name":"button_link","label":"Button Link","type":"url"},{"name":"button_text","label":"Button Text","type":"text","default":""},{"name":"button_icon","label":"Icon","type":"icons","label_block":true,"fa4compatibility":"icon"}]},{"name":"style_section","label":"Style Settings","tab":"style","controls":[{"name":"text_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"prefix_class":"elementor-align-","default":"","selectors":{"{{WRAPPER}} .pxl-pricing-single":"text-align: {{VALUE}};"}},{"name":"price_color","label":"Price Color","type":"color","selectors":{"{{WRAPPER}} .pxl-pricing-single .pricing-price":"color: {{VALUE}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-pricing-single .pricing-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-pricing-single .pricing-title"},{"name":"feature_color","label":"Feature Color","type":"color","selectors":{"{{WRAPPER}} .pxl-pricing-single .pricing-feature":"color: {{VALUE}};"}},{"name":"feature_icon_color","label":"Feature Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-pricing-single .pricing-feature li:before":"color: {{VALUE}};"}},{"name":"closed_feature_icon_color","label":"Closed Feature Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-pricing-single .pricing-feature li.no-active:before":"color: {{VALUE}};"}},{"name":"feature_typography","label":"Feature Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-pricing-single .pricing-feature"},{"name":"item_highlight","label":"Highlight","type":"select","options":{"highlight-none":"No","highlight-active":"Yes"},"default":"highlight-none"},{"name":"highlight_text","label":"Highlight Text","type":"text","default":"BEST","label_block":true,"condition":{"item_highlight":"highlight-active"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}