<?php

class PxlQuickcontact_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_quickcontact';
    protected $title = 'PXL Quick Contact';
    protected $icon = 'eicon-mail';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_quickcontact-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/theme_powerlegal\/wp-content\/themes\/powerlegal\/elements\/register\/img-layout\/pxl_quickcontact-2.jpg"}},"prefix_class":"pxl-quick-contact-layout-"}]},{"name":"content_section","label":"Content Settings","tab":"content","controls":[{"name":"contact_list","label":"Contact Lists","type":"repeater","controls":[{"name":"pxl_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"pxli pxli-marker-alt","library":"pxli-icon"}},{"name":"item_title","label":"Item Title","type":"textarea","placeholder":"Enter item title","default":"59 Main Street, USA","label_block":true}],"default":[{"pxl_icon":{"value":"pxli pxli-phone-alt1","library":"pxli-icon"},"item_title":"+012 (345) 56 998"},{"pxl_icon":{"value":"pxli pxli-envelope-regular","library":"pxli-icon"},"item_title":"support@gmail.com"},{"pxl_icon":{"value":"pxli pxli-marker-alt","library":"pxli-icon"},"item_title":"59 Main Street, USA"}]}]},{"name":"qc_style","label":"Style","tab":"style","controls":[{"name":"qc_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-qc-wrap":"justify-content: {{VALUE}};"}},{"name":"heading_text_color","label":"Heading Color","type":"color","selectors":{"{{WRAPPER}} .qc-title":"color: {{VALUE}};"}},{"name":"item_text_color","label":"Content item Color","type":"color","selectors":{"{{WRAPPER}} .qc-desc-wrap":"color: {{VALUE}};"}},{"name":"item_icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .qc-desc-wrap .pxl-icon":"color: {{VALUE}};"}},{"name":"heading_typography","label":"Heading Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .qc-title"},{"name":"item_typography","label":"Item text Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .qc-desc-wrap"},{"name":"item_animation","label":"Item Motion Effect","type":"animation","condition":[]},{"name":"item_animation_duration","label":"Item Animation Duration","type":"select","default":"normal","options":{"slow":"Slow","normal":"Normal","fast":"Fast"},"condition":{"item_animation!":""}},{"name":"item_animation_delay","label":"Item Animation Delay","type":"number","min":0,"step":100,"condition":{"item_animation!":""}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}