<?php
/**
 * ACF field group: Front Page (Hero, Fancy boxes). No Elementor.
 *
 * @package Molochko
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

acf_add_local_field_group( array(
	'key'                   => 'group_molochko_front_page',
	'title'                 => __( 'Головна сторінка (Molochko)', 'molochko' ),
	'fields'                => array(
		array(
			'key'           => 'field_molochko_hero_shortcode',
			'label'         => __( 'Шорткод слайдера (Hero)', 'molochko' ),
			'name'          => 'hero_slider_shortcode',
			'type'          => 'text',
			'instructions'  => __( 'Наприклад [rev_slider alias="slider-1"] або будь-який шорткод для блоку Hero.', 'molochko' ),
			'default_value' => '[rev_slider alias="slider-1"]',
			'placeholder'   => '[rev_slider alias="slider-1"]',
		),
		array(
			'key'        => 'field_molochko_fancy_boxes',
			'label'      => __( 'Картки (3 блоки)', 'molochko' ),
			'name'       => 'fancy_boxes',
			'type'       => 'repeater',
			'layout'     => 'block',
			'min'        => 0,
			'max'        => 6,
			'button_label' => __( 'Додати блок', 'molochko' ),
			'sub_fields' => array(
				array(
					'key'           => 'field_fb_icon',
					'label'         => __( 'Іконка (CSS класи)', 'molochko' ),
					'name'          => 'icon',
					'type'          => 'text',
					'instructions'  => __( 'Наприклад flaticon flaticon-calling або flaticon flaticon-award. Ігнорується, якщо задано зображення іконки.', 'molochko' ),
					'default_value' => 'flaticon flaticon-calling',
				),
				array(
					'key'           => 'field_fb_icon_image',
					'label'         => __( 'Іконка (зображення/SVG)', 'molochko' ),
					'name'          => 'icon_image',
					'type'          => 'image',
					'return_format' => 'array',
					'preview_size'  => 'thumbnail',
					'instructions'  => __( 'Опціонально. Якщо задано — використовується замість CSS-класів іконки.', 'molochko' ),
				),
				array(
					'key'   => 'field_fb_title',
					'label' => __( 'Заголовок', 'molochko' ),
					'name'  => 'title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_fb_description',
					'label' => __( 'Опис', 'molochko' ),
					'name'  => 'description',
					'type'  => 'textarea',
					'rows'  => 3,
				),
				array(
					'key'   => 'field_fb_button_text',
					'label' => __( 'Текст кнопки', 'molochko' ),
					'name'  => 'button_text',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_fb_link',
					'label' => __( 'Посилання', 'molochko' ),
					'name'  => 'link',
					'type'  => 'link',
				),
				array(
					'key'          => 'field_fb_image',
					'label'        => __( 'Зображення (опціонально)', 'molochko' ),
					'name'         => 'image',
					'type'         => 'image',
					'return_format' => 'array',
					'preview_size' => 'medium',
				),
			),
		),
		array(
			'key'   => 'field_molochko_about_tab',
			'label' => __( 'Блок «Про нас»', 'molochko' ),
			'name'  => 'about_tab',
			'type'  => 'tab',
		),
		array(
			'key'          => 'field_about_image_bg',
			'label'        => __( 'Про нас: фонове зображення (ліва колонка)', 'molochko' ),
			'name'         => 'about_image_bg',
			'type'         => 'image',
			'return_format' => 'array',
			'preview_size' => 'medium',
		),
		array(
			'key'          => 'field_about_image_person',
			'label'        => __( 'Про нас: фото персони/CEO (накладення)', 'molochko' ),
			'name'         => 'about_image_person',
			'type'         => 'image',
			'return_format' => 'array',
			'preview_size' => 'medium',
		),
		array(
			'key'   => 'field_about_subtitle',
			'label' => __( 'Про нас: підзаголовок', 'molochko' ),
			'name'  => 'about_subtitle',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_about_title',
			'label' => __( 'Про нас: заголовок (H2)', 'molochko' ),
			'name'  => 'about_title',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_about_description',
			'label' => __( 'Про нас: основний текст', 'molochko' ),
			'name'  => 'about_description',
			'type'  => 'wysiwyg',
		),
		array(
			'key'   => 'field_about_cta_line',
			'label' => __( 'Про нас: заклик до дії (напр. Дзвоніть 24/7...)', 'molochko' ),
			'name'  => 'about_cta_line',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_about_contact_line',
			'label' => __( 'Про нас: контактний рядок (телефон + посилання, дозволений HTML)', 'molochko' ),
			'name'  => 'about_contact_line',
			'type'  => 'wysiwyg',
		),
		array(
			'key'   => 'field_about_name',
			'label' => __( 'Про нас: ім\'я персони', 'molochko' ),
			'name'  => 'about_name',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_about_role',
			'label' => __( 'Про нас: посада', 'molochko' ),
			'name'  => 'about_role',
			'type'  => 'text',
		),
		array(
			'key'   => 'field_molochko_practice_areas_tab',
			'label' => __( 'Секція «Напрямки практики»', 'molochko' ),
			'name'  => 'practice_areas_tab',
			'type'  => 'tab',
		),
		array(
			'key'           => 'field_practice_areas_subtitle',
			'label'         => __( 'Напрямки практики: підзаголовок', 'molochko' ),
			'name'          => 'practice_areas_subtitle',
			'type'          => 'text',
			'default_value' => 'Наша експертиза',
		),
		array(
			'key'           => 'field_practice_areas_title',
			'label'         => __( 'Напрямки практики: заголовок (H2)', 'molochko' ),
			'name'          => 'practice_areas_title',
			'type'          => 'text',
			'default_value' => 'Напрямки юридичної практики',
		),
		array(
			'key'           => 'field_practice_areas_description',
			'label'         => __( 'Напрямки практики: опис', 'molochko' ),
			'name'          => 'practice_areas_description',
			'type'          => 'textarea',
			'rows'          => 3,
			'default_value' => 'Надаємо кваліфіковану юридичну допомогу у кримінальних справах, спорах через ДТП, військових питаннях, сімейних та трудових спорах. Маємо значний досвід у цих напрямках та гарантуємо індивідуальний підхід до кожної справи.',
		),
		array(
			'key'           => 'field_practice_areas_items',
			'label'         => __( 'Напрямки практики: картки сітки', 'molochko' ),
			'name'          => 'practice_areas',
			'type'          => 'repeater',
			'layout'        => 'block',
			'min'           => 0,
			'max'           => 50,
			'button_label'  => __( 'Додати напрямок практики', 'molochko' ),
			'instructions'  => __( 'Якщо заповнено — цей список не використовується; секція показує записи типу «Напрямки практики» (pxl-practice-area).', 'molochko' ),
			'sub_fields'    => array(
				array(
					'key'   => 'field_pa_item_title',
					'label' => __( 'Заголовок', 'molochko' ),
					'name'  => 'title',
					'type'  => 'text',
				),
				array(
					'key'   => 'field_pa_item_description',
					'label' => __( 'Опис', 'molochko' ),
					'name'  => 'description',
					'type'  => 'textarea',
					'rows'  => 2,
				),
				array(
					'key'           => 'field_pa_item_icon',
					'label'         => __( 'Іконка (CSS клас)', 'molochko' ),
					'name'          => 'icon',
					'type'          => 'text',
					'default_value' => 'flaticon flaticon-businessman',
					'placeholder'   => 'flaticon flaticon-businessman',
				),
				array(
					'key'          => 'field_pa_item_icon_image',
					'label'        => __( 'Іконка (зображення, опціонально)', 'molochko' ),
					'name'         => 'icon_image',
					'type'         => 'image',
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
				),
				array(
					'key'   => 'field_pa_item_link',
					'label' => __( 'Посилання', 'molochko' ),
					'name'  => 'link',
					'type'  => 'link',
				),
			),
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'page_type',
				'operator' => '==',
				'value'    => 'front_page',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
	'active'                => true,
	'show_in_rest'          => 1,
	'description'           => __( 'Hero та картки для головної сторінки Molochko. Замінює Elementor на головній.', 'molochko' ),
) );
